import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import partners from '../public/img/partners.png'
import first from '../public/img/first.jpg'
import second from '../public/img/second.jpg'
import third from '../public/img/third.jpg'
import last from '../public/img/last.jpg'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stream Tv and Movies Live</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <nav className={styles.navbar}>
          <h1>Log in</h1>
          <div className={styles.center}>
            <h5>buNDLE WITH ANY HULU PLAN & SAVE</h5>
          <Image src={partners} width={680} height={260} alt="partners"/>
          <p>Get endless entertainment, live sports, and <br /> the shows and movies you love.</p>
            <button>Get the disney bundle</button> <br />
            <small>What's included? <span>See</span> Bundle terms.</small>
            <h6>Sign up for Hulu only</h6>
          </div>
          </nav>

          <div className={styles.main}>
            <h5>INCLUDED IN ALL PLANS</h5>
            <h1>All The TV You Love</h1>
            <h2>Stream full seasons of exclusive series, current-season episodes, hit movies, Hulu <br /> Originals, kids shows, and more.</h2>
            <div className={styles.boxs}>
              <div className={styles.box}>
                <Image  width={320} height={450}  src={first} alt="image"/>
                <p>
Past & Current Seasons <br />
<span>TV Shows</span></p>
              </div>
              <div className={styles.box}>
                <Image width={320} height={450}  src={second} alt="image"/>
                <p>
New & Classic <br />
<span>Movies</span></p>
              </div>
              <div className={styles.box}>
                <Image  width={320} height={450} src={third} alt="image"/>
                <p>
Groundbreaking <br />
<span>Hulu Originals</span></p>
              </div>
              <div className={styles.box}>
                <Image width={320} height={450}  src={last} alt="image"/>
              <p>
Add-on <br />
<span>Premiums</span></p>
              </div>
            </div>
            <div className={styles.lives}>
              <small>HULU + LIVE TV, NOW WITH DISNEY+ AND ESPN+</small>
              <h1>Live TV Makes It Better</h1>
              <p>Make the switch from cable. Get 75+ top channels on Hulu with your favorite live sports, news, and events - plus the entire Hulu streaming library. Access endless entertainment with Disney+ and live sports with ESPN+. All three for a new price of $69.99/month.</p>
            <span>18+ only. Regional restrictions, blackouts and Live TV terms apply. Access content from each service separately and access ESPN+ content via Hulu. Location data required to watch <br /> certain content. Offer valid for eligible subscribers only. </span>
            <h6>VIEW CHANNELS IN YOUR AREA →</h6>
           </div>
           <div className={styles.footer}>
            <div className={styles.farent}>
              <ul>
                <li className={styles.line}>BROWSE</li>
                <li className={styles.line}>Streaming Library</li>
                <li className={styles.line}>Live TV</li>
                <li className={styles.line}>Live News</li>
                <li className={styles.line}>Live Sports</li>
              </ul>

              <ul>
                <li className={styles.line}>Tv Shows</li>
                <li className={styles.line}>Movies</li>
                <li className={styles.line}>Originals</li>
                <li className={styles.line}>Networks</li>
                <li className={styles.line}>Kids</li>
                <li className={styles.line}>Fx</li>
              </ul>


              <ul>
                <li className={styles.line}>Hbo Max</li>
                <li className={styles.line}>Cinemax</li>
                <li className={styles.line}>ShowTime</li>
                <li className={styles.line}>STARS</li>
              </ul>

              <ul>
                <li className={styles.line}>Hulu,Disney & espagnol+</li>
                <li className={styles.line}>Hulu (No Ads)</li>
                <li className={styles.line}>Student Discount</li>
              </ul>

              <ul>
                <li className={styles.line}>HELP</li>
                <li className={styles.line}>Account and Biling</li>
                <li className={styles.line}>Plans and Pricing</li>
                <li className={styles.line}>Supported Devices</li>
                <li className={styles.line}>Accessipelity</li>
              </ul>
              <ul>
                <li className={styles.line}>About Us</li>
                <li className={styles.line}>Shop Hulu</li>
                <li className={styles.line}>Press</li>
                <li className={styles.line}>Jobs</li>
                <li className={styles.line}>Contact</li>
              </ul>
           
            </div>
          </div>
          </div>
         
          </div>
          
    </div>
  )
}
